### ISSUE TITLE
Failing `databricks bundle destroy` without existing resources

### ISSUE THREAD

**Issue by JasperGrs** [databricks/setup-cli#105]
A Github Actions job executing the `databricks bundle destroy` command fails when no databricks resources exist within the workspace due to missing terraform state file. This means that a pre-emptive execution of the command to guarantee a clean workspace (regarding asset bundle resources) before deploying new resources becomes impossible.

Note: The used version is @ main, which references to tag [v0.219.0](https://github.com/databricks/setup-cli/releases/tag/v0.219.0) when I came upon the issue.
during writing the newer tag [v0.220.0](https://github.com/databricks/setup-cli/releases/tag/v0.220.0) got released. Some testing shows that the issue persists in this version

### actions.yml file
(`databricks bundle validate` included to prove correct bundle configuration)
```
name: "Databricks asset bundle test"
concurrency: 1
on:
  push:
    branches:
      - CICD-POC

jobs:
  validate:
    name: "Validate asset bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: 
          databricks bundle validate --debug
        working-directory: ./
        env:
          DATABRICKS_TOKEN: ${{ secrets.***}}
          BUNDLE_VAR_SQL_WAREHOUSE_ID: ${{ secrets.***}}
          BUNDLE_VAR_COMPUTE_ID: ${{ secrets.***}}
          DATABRICKS_HOST: ${{ secrets.***}}
    
  delete:
    name: "destroy existing asset bundles items"
    runs-on: ubuntu-latest
    needs: 
      - validate
    steps:

      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: 
          databricks bundle destroy --auto-approve
        working-directory: ./
        env:
          DATABRICKS_TOKEN: ${{ secrets.***}}
          BUNDLE_VAR_SQL_WAREHOUSE_ID: ${{ secrets.***}}
          BUNDLE_VAR_COMPUTE_ID: ${{ secrets.***}}
          DATABRICKS_HOST: ${{ secrets.***}
```
### Result with existing resources (by locally running `databricks bundle deploy` before executing the Github actions workflow)
![image](https://github.com/databricks/setup-cli/assets/43341055/b69732e9-53ad-4284-a515-a2e2c516ffae)

### Result without existing resources
![image](https://github.com/databricks/setup-cli/assets/43341055/467bcab9-7733-46be-bd2b-5f508e1ba5ce)
