### ISSUE TITLE
Add optional "version" input

### ISSUE THREAD

**Issue by connorbrown-8451** [databricks/setup-cli#30]
It would be nice to have an optional "version" input for this action that allows users to pin the version of the Databricks CLI to a specific release.

For example:
```yaml
steps:
  - uses: databricks/setup-cli@main
    with:
      version: '0.201.0'
```

If the input is not provided, I think it should default to the "latest" version if possible.
