### ISSUE TITLE
Failing `databricks bundle deploy` command on the latest versions of the action

### ISSUE THREAD

**Issue by leonardovida** [databricks/setup-cli#89]
Hi there,

I'm running a simple workflow to deploy databricks asset bundles. On the latest versions of the cli the command `databricks bundle deploy -t <any bundle env here>` fails.

I didn't test extensively, but the version that is works for me is the @b6fadede636e814af275367aa1a10198a7d2df6f (so [v0.211.0](https://github.com/databricks/setup-cli/releases/tag/v0.211.0). But again, I didn't test extensively the versions above that one.

My current working setup is the following:

```
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "The runner to use"
      working-directory:
        required: false
        type: string
        default: "."
        description: "The working directory to use"
      databricks-bundle-env:
        required: false
        type: string
        default: "staging"
        description: "The environment to deploy the bundle to"
      python-version: 
        required: false
        type: string
        default: "3.11.7"
        description: "Python version"
      poetry-version:
        required: false
        type: string
        default: "1.7.1"
        description: "Poetry version"

jobs:
  deploy:
    name: "Deploy bundle to ${{ inputs.databricks-bundle-env }}"
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
        
      - uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}
      
      - uses: databricks/setup-cli@b6fadede636e814af275367aa1a10198a7d2df6f
          
      - shell: bash
        run: |
          databricks bundle deploy -t ${{ inputs.databricks-bundle-env }}
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BUNDLE_ENV: ${{ inputs.databricks-bundle-env }}
```

which is then called in a similar way as this one

```
name: "Deploy to staging"
concurrency: 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-job:
    uses: pia-group-nl/pia-github-actions/.github/workflows/databricks-bundle.yml@main
    secrets:
      inherit
    with:
      # The environment to deploy to
      # Note: this calls the Github environment variables set on Github
      environment: "staging"
      databricks-bundle-env: 'staging'

[other jobs]
```
